version: '3'
services:
  # presto:
  #   hostname: presto
  #   image: 'starburstdata/presto:0.203-e.0.1'
  #   container_name: presto
  #   ports:
  #     - '8080:8080'
  #   volumes: 
  #     - './presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
  #     - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/presto/lib/plugin/hive-hadoop2/json-serde-1.3.8-jar-with-dependencies.jar'
  # hadoop:
  #   hostname: hadoop-master
  #    image: 'prestodb/cdh5.13-hive:latest'
  #  container_name: hadoop-master
  #   volumes:
  #     - './hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml'
  #     - './hadoop/lib/json-udf-1.3.8-jar-with-dependencies.jar:/usr/lib/hive/lib/json-udf-1.3.8-jar-with-dependencies.jar'
  #     - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/hive/lib/json-serde-1.3.8-jar-with-dependencies.jar'
  # hadoop-master:
  #   hostname: hadoop-master
  #   build:
  #     context: hadoop
  #   container_name: hadoop-master
  #   ports:
  #     - '9870:9870'
  hive:
    build: hive
    hostname: hive
    container_name: hive
    environment:
      DB_URI: mariadb:3306
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10
    hostname: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mariadb.conf:/etc/mysql/conf.d/mariadb.conf
  # hive:
  #   hostname: hive
  #   build:
  #     context: .
  #     dockerfile: hive-minimal/Dockerfile
  #   container_name: hive
  #   ports: []
  #   environment:
  #     AWS_ACCESS_KEY_ID: V42FCGRVMK24JJ8DHUYG
  #     AWS_SECRET_ACCESS_KEY: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
  presto:
    hostname: presto
    build:
      context: .
      dockerfile: prestodb/Dockerfile
    container_name: presto
    ports:
      - '8080:8080'
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio/data/:/data'
      # - './minio/config:/root/.minio'
    environment:
      MINIO_ACCESS_KEY: V42FCGRVMK24JJ8DHUYG
      MINIO_SECRET_KEY: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
    command: server /data --console-address ":9001"
